FROM tensorflow/tensorflow

RUN apt-get update && \
     apt-get install python-tk -y
# docker run --name irace -it -v C:/Users/luis.alves/Documents/TCC:/app -w /app luisfrsa/irace bash
WORKDIR "/home/tensorflow"


# docker run --name tensorflow \
#             -it -v /home/luis_adm/Documents/projetos/tensorflow:/home/tensorflow \
#             -w /home/tensorflow \
#             tensorflow/tensorflow \
#             bash
